services:
  - type: web
    name: librescript-ide
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 18
    autoDeploy: true
    branch: main
